title: 'Udemy Ramda Course Notes'
subtitle: 'notes for the online course avaliable on Udemy.com'

markdown: kramdown

kramdown:
  hard_wrap: true
  input: GFM

highlighter: rouge

exclude:
- README.md
- LICENSE.md
